// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLy_PhongTro.Repository;

#nullable disable

namespace QuanLy_PhongTro.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250506164805_adddata")]
    partial class adddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLy_PhongTro.Models.AnhPhongTroModel", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LaAnhDaiDien")
                        .HasColumnType("bit");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaPhong");

                    b.ToTable("AnhPhongTros");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.ChiSoDienNuocModel", b =>
                {
                    b.Property<int>("MaChiSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiSo"));

                    b.Property<decimal>("ChiSoDienCu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChiSoDienMoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChiSoNuocCu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChiSoNuocMoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("MaChiSo");

                    b.HasIndex("MaHopDong");

                    b.ToTable("ChiSoDienNuoc");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.HoaDonModel", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int?>("MomoId")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienRac")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa thanh toán");

                    b.Property<int?>("VnpayId")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MomoId")
                        .IsUnique()
                        .HasFilter("[MomoId] IS NOT NULL");

                    b.HasIndex("VnpayId")
                        .IsUnique()
                        .HasFilter("[VnpayId] IS NOT NULL");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.HopDongModel", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaPhong");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.LoaiPhongModel", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.LuuPhongModel", b =>
                {
                    b.Property<int>("MaLuuPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuuPhong"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLuu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaLuuPhong");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaPhong");

                    b.ToTable("LuuPhongs");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.MomoModel", b =>
                {
                    b.Property<int>("MomoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MomoId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderInfo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MomoId");

                    b.HasIndex("MaHopDong");

                    b.ToTable("MomoInfor");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.NguoiDungModel", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaQuyen");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.PhanQuyenModel", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.PhongTroModel", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("DienTich")
                        .HasColumnType("real");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("PhongTro");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.PhongTro_ThietBiModel", b =>
                {
                    b.Property<int>("MaPhongThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongThietBi"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhongThietBi");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaThietBi");

                    b.ToTable("PhongTro_ThietBi");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.ThietBiModel", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThietBi");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.VnpayModel", b =>
                {
                    b.Property<int>("VnpayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VnpayId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<string>("OrderDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VnpayId");

                    b.HasIndex("MaHopDong");

                    b.ToTable("VnPayInfor");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.AnhPhongTroModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.PhongTroModel", "PhongTro")
                        .WithMany("AnhPhongTros")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.ChiSoDienNuocModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.HopDongModel", "HopDong")
                        .WithMany("ChiSoDienNuocs")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.HoaDonModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.HopDongModel", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLy_PhongTro.Models.MomoModel", "Momo")
                        .WithOne()
                        .HasForeignKey("QuanLy_PhongTro.Models.HoaDonModel", "MomoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLy_PhongTro.Models.VnpayModel", "Vnpay")
                        .WithOne()
                        .HasForeignKey("QuanLy_PhongTro.Models.HoaDonModel", "VnpayId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HopDong");

                    b.Navigation("Momo");

                    b.Navigation("Vnpay");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.HopDongModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLy_PhongTro.Models.PhongTroModel", "PhongTro")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.LuuPhongModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("LuuPhongs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLy_PhongTro.Models.PhongTroModel", "PhongTro")
                        .WithMany("LuuPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.MomoModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.HopDongModel", "HopDong")
                        .WithMany("MomoPayments")
                        .HasForeignKey("MaHopDong");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.NguoiDungModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.PhanQuyenModel", "PhanQuyen")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.PhongTroModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.LoaiPhongModel", "LoaiPhong")
                        .WithMany("PhongTros")
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.PhongTro_ThietBiModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.PhongTroModel", "PhongTro")
                        .WithMany("PhongTroThietBis")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLy_PhongTro.Models.ThietBiModel", "ThietBi")
                        .WithMany("PhongTroThietBis")
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongTro");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.VnpayModel", b =>
                {
                    b.HasOne("QuanLy_PhongTro.Models.HopDongModel", "HopDong")
                        .WithMany("VnpayPayments")
                        .HasForeignKey("MaHopDong");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.HopDongModel", b =>
                {
                    b.Navigation("ChiSoDienNuocs");

                    b.Navigation("HoaDons");

                    b.Navigation("MomoPayments");

                    b.Navigation("VnpayPayments");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.LoaiPhongModel", b =>
                {
                    b.Navigation("PhongTros");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.NguoiDungModel", b =>
                {
                    b.Navigation("HopDongs");

                    b.Navigation("LuuPhongs");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.PhanQuyenModel", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.PhongTroModel", b =>
                {
                    b.Navigation("AnhPhongTros");

                    b.Navigation("HopDongs");

                    b.Navigation("LuuPhongs");

                    b.Navigation("PhongTroThietBis");
                });

            modelBuilder.Entity("QuanLy_PhongTro.Models.ThietBiModel", b =>
                {
                    b.Navigation("PhongTroThietBis");
                });
#pragma warning restore 612, 618
        }
    }
}
